language: scala

matrix:
  fast_finish: true
  include:
  - scala: 2.11.12
    jdk: oraclejdk8
    script: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck scalastyle test:scalastyle

  - scala: 2.11.12
    jdk: oraclejdk8
    script: sbt mimaReportBinaryIssues

  - scala: 2.11.12
    jdk: oraclejdk8
    script: sbt coverage "++$TRAVIS_SCALA_VERSION test" coverageReport coverageAggregate
    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - scala: 2.12.6
    jdk: oraclejdk8
    script: sbt "++$TRAVIS_SCALA_VERSION test"

  allow_failures:
  - scala: 2.11.12
    jdk: oraclejdk8
    script: sbt mimaReportBinaryIssues

cache:
  directories:
  - $HOME/.sbt/boot
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delet

notifications:
  email:
  - flatmap-squad@spotify.com
