version: 2.1

scala_211: &scala_211
  environment:
    - SCALA_VERSION: 2.11.12

scala_212: &scala_212
  environment:
    - SCALA_VERSION: 2.12.10

jdk8: &jdk8
  docker:
    - image: circleci/openjdk:8-jdk

commands:
  build_featran:
    parameters:
      build-steps:
        description: "build steps"
        type: steps
        default: []
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - steps: << parameters.build-steps >>
      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}
          paths:
          - "~/.ivy2/cache"
          - "~/.sbt"
          - "~/.m2"
          - "~/.cache/coursier"

settings: &settings
  working_directory: ~/featran
  resource_class: xlarge

jobs:
  checks:
    <<: [*settings, *scala_211, *jdk8]
    steps:
    - build_featran:
        build-steps:
          - run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck scalastyle test:scalastyle
  mima_report:
    <<: [*settings, *scala_211, *jdk8]
    steps:
    - build_featran:
        build-steps:
          - run: sbt mimaReportBinaryIssues
  build_211:
    <<: [*settings, *scala_211, *jdk8]
    steps:
      - build_featran:
          build-steps:
            - run: sbt coverage "++$SCALA_VERSION test" coverageReport coverageAggregate
            - run: bash <(curl -s https://codecov.io/bash)
  build_212:
    <<: [*settings, *scala_212, *jdk8]
    steps:
    - build_featran:
        build-steps:
          - run: sbt "++$SCALA_VERSION test"

  publish:
    <<: [*settings, *scala_211, *jdk8]
    steps:
    - build_featran:
        build-steps:
          - run: sbt +publish

workflows:
  version: 2
  build:
    jobs:
      - checks
      - mima_report
      - build_211:
          requires:
            - checks
            - mima_report
      - build_212:
          requires:
            - checks
            - mima_report

      - publish:
          requires:
            - build_211
            - build_212
          filters:
            branches:
              only:
                - master
