name: ci
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: Java 11 setup
        uses: olafurpg/setup-scala@v11
        with:
          java-version: 1.11.0
      - run: sbt "; scalafmtCheckAll; scalafmtSbtCheck" "; scalafixEnable; scalafixAll --check"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{matrix.java}}
      - if: startsWith(matrix.scala,'2.12')
        # sbt-scoverage is not yet compatible with 2.12.13
        # https://github.com/scoverage/sbt-scoverage/issues/319
        run: |
          sbt coverage "++2.12.12 test" coverageReport
          bash <(curl -s https://codecov.io/bash)
      - if: "!startsWith(matrix.scala,'2.12')"
        run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - 1.8.0
          - 1.11.0
        scala:
          - 2.12.13
          - 2.13.5
          - 3.0.0-M3
  mimaReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v6
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} mimaReportBinaryIssues"
    strategy:
      matrix:
        java:
          - 1.8.0
          - 1.11.0
        scala:
          - 2.12.13
          - 2.13.5
